Allow default namespace, stop on errors, debug-only flag

diff --git a/kubectl-execuser b/kubectl-execuser
--- a/kubectl-execuser
+++ b/kubectl-execuser
@@ -1,38 +1,41 @@
 #!/usr/bin/env bash
 
-function usage() {
-    echo "kubectl execuser pod [(-u|--username=)|(-n|--namespace=)|(-l|--label=)|(-c|--container-index=)|(-t|--tolerations=)|(-s|--shell=)|(-v|--verbose)|(-h|--help)]"
-}
+set -e
 
+function usage() {
+  echo "kubectl execuser pod [(-u|--username=)|(-n|--namespace=)|(-c|--container-index=)|(-s|--shell=)|(-t|--tolerations)|(-d|--debug-only)|(-v|--verbose)|(-h|--help)]"
+}
+VARS="`set -o posix ; set`";
+ARGS="${@}"
 POD=${1}
-USER="root"
+POD_USER="root"
 COMMAND="sh"
-NAMESPACE=$(kubectl config view --minify -o 'jsonpath={..namespace}')
-SEL_LABEL="k8s-app"
+CURRENT_NAMESPACE=$(kubectl config view --minify -o 'jsonpath={..namespace}')
+NAMESPACE="${CURRENT_NAMESPACE:-default}"
 CONTAINER_INDEX=0
 VERBOSE=false
 
-if [[ $# -lt 1 || $POD == -* ]]; then
+if [ $# -lt 1 ] || [ -z "$POD" ] ; then
     usage
     exit 1
 fi
 
-OPTS=`getopt -o u:n:l:s:c:htv -l "username:namespace:label:shell:index:help,tolerations,verbose," -n "kubectl-execuser" -- "${@:2}"`
+OPTS=`getopt -o u:n:s:c:dhtv -l "username:namespace:shell:index:debug,help,tolerations,verbose," -n "kubectl-execuser" -- "${@:2}"`
 
-[ $? -eq 0 ] || {
+if [ $? -ne 0 ] ; then
     usage
     exit 1
-}
+fi
 
 eval set -- "$OPTS"
 
 while true; do
   case "$1" in
+    -d | --debug-only ) DEBUG=true; shift ;;
     -h | --help ) HELP=true; shift ;;
-    -l | --label ) SEL_LABEL=${2:-$SEL_LABEL}; shift; shift ;;
     -n | --namespace ) NAMESPACE=${2:-$NAMESPACE}; shift; shift ;;
     -s | --shell ) COMMAND="${2:-$COMMAND}"; shift; shift ;;
-    -u | --username ) USER=$2; shift; shift ;;
+    -u | --username ) POD_USER=$2; shift; shift ;;
     -c | --container-index ) CONTAINER_INDEX_ARG=true; CONTAINER_INDEX=${2:-${CONTAINER_INDEX}}; shift; shift ;;
     -t | --tolerations ) ENABLE_TOLERATIONS=true; shift ;;
     -v | --verbose ) VERBOSE=true; shift ;;
@@ -40,6 +43,13 @@ while true; do
     * ) break ;;
   esac
 done
+
+if [ "$DEBUG" = true ] ; then
+    echo "$VARS"
+    SCRIPT_VARS="`grep -vFe "$VARS" <<<"$(set -o posix ; set)" | grep -v ^VARS=`";
+    echo "$SCRIPT_VARS"
+    exit 0
+fi
 
 # Print help
 if [ "${HELP:-false}" = true ] ; then
@@ -55,8 +65,8 @@ CONTAINERS="$(kubectl get po -n $NAMESPACE $POD -o "jsonpath={range .status.cont
 NUM_CONTAINERS=$(echo "$CONTAINERS" | wc -l)
 
 if [ "$NUM_CONTAINERS" -gt 1 ] && [ "$CONTAINER_INDEX_ARG" != true ]; then
-  echo "Container index arg missing. Defaulting to index 0."
-  echo "Consider passing argument (-c|--container-index) to exec into a different container"
+  echo "Container index arg missing. Defaulting to index 0,"
+  echo "consider passing the opt argument (-c|--container-index) to specify a different container"
   echo "$CONTAINERS" | awk 'BEGIN{line=0}{printf "\t%d) %s\n", line++, $0}'
 fi
 
@@ -64,20 +74,21 @@ EXECUSER_POD="execuser-${POD}"
 EXECUSER_POD=${EXECUSER_POD:0:63}  # Truncate to 64 char
 
 NODENAME=$( kubectl -n ${NAMESPACE} get pod ${POD} -o go-template='{{.spec.nodeName}}' )
-DOCKER_CONTAINERID=$( kubectl -n ${NAMESPACE} get pod ${POD} -o go-template="{{ (index .status.containerStatuses ${CONTAINER_INDEX}).containerID }}" )
-CONTAINERID=${DOCKER_CONTAINERID#*//}
+DOCKER_CONTAINER_ID=$( kubectl -n ${NAMESPACE} get pod ${POD} -o go-template="{{ (index .status.containerStatuses ${CONTAINER_INDEX}).containerID }}" )
+CONTAINER_ID=${DOCKER_CONTAINER_ID#*//}
 
 if [ "$ENABLE_TOLERATIONS" = true ]; then
-read -r -d '' TOLERATIONS << EOF
+
+(read -r -d '' TOLERATIONS << EOM
         "tolerations": [
-          {
-               "key": "node-role.kubernetes.io/master"
-          }
+          { "key": "node-role.kubernetes.io/master" }
         ],
-EOF
+EOM
+) || true
+
 fi
 
-read -r -d '' CONTAINER_SPEC << EOF
+(read -r -d '' CONTAINER_SPEC << EOM
 {
     "apiVersion": "v1",
     "metadata": {
@@ -109,8 +120,8 @@ read -r -d '' CONTAINER_SPEC << EOF
                   "exec",
                   "-it",
                   "-u",
-                  "${USER}",
-                  "${CONTAINERID}",
+                  "${POD_USER}",
+                  "${CONTAINER_ID}",
                   "${COMMAND}"
                 ],
                 "volumeMounts": [
@@ -136,7 +147,8 @@ read -r -d '' CONTAINER_SPEC << EOF
         ]
     }
 }
-EOF
+EOM
+) || true
 
 kubectl delete pods -n ${NAMESPACE} -l run="${EXECUSER_POD}" --grace-period 0 &>/dev/null
 kubectl run -n ${NAMESPACE} -it --rm --restart=Never --image=docker --overrides="${CONTAINER_SPEC}" ${EXECUSER_POD}
